# coding: utf-8

"""
    NauticalStream | workspace-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nauticalstream_workspace.models.update_workspace_request import UpdateWorkspaceRequest

class TestUpdateWorkspaceRequest(unittest.TestCase):
    """UpdateWorkspaceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateWorkspaceRequest:
        """Test UpdateWorkspaceRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateWorkspaceRequest`
        """
        model = UpdateWorkspaceRequest()
        if include_optional:
            return UpdateWorkspaceRequest(
                status = 'draft',
                type = 'unspecified',
                name = '',
                handle = '',
                description = '',
                category_id = 56,
                formatted_address = '',
                location = nauticalstream_workspace.models.point.Point(
                    latitude = 1.337, 
                    longitude = 1.337, ),
                avatar_id = '',
                cover_id = ''
            )
        else:
            return UpdateWorkspaceRequest(
        )
        """

    def testUpdateWorkspaceRequest(self):
        """Test UpdateWorkspaceRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
