# coding: utf-8

"""
    NauticalStream | workspace-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nauticalstream_workspace.models.amenity_filters import AmenityFilters

class TestAmenityFilters(unittest.TestCase):
    """AmenityFilters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AmenityFilters:
        """Test AmenityFilters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AmenityFilters`
        """
        model = AmenityFilters()
        if include_optional:
            return AmenityFilters(
                category_id = 56,
                status = 'pending',
                name = '',
                key = ''
            )
        else:
            return AmenityFilters(
        )
        """

    def testAmenityFilters(self):
        """Test AmenityFilters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
