# coding: utf-8

"""
    NauticalStream | workspace-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nauticalstream_workspace.models.list_workspaces_request import ListWorkspacesRequest

class TestListWorkspacesRequest(unittest.TestCase):
    """ListWorkspacesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListWorkspacesRequest:
        """Test ListWorkspacesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListWorkspacesRequest`
        """
        model = ListWorkspacesRequest()
        if include_optional:
            return ListWorkspacesRequest(
                pagination = nauticalstream_workspace.models.page_request.PageRequest(
                    page = 56, 
                    size = 56, ),
                filters = nauticalstream_workspace.models.workspace_filters.WorkspaceFilters(
                    status = 'draft', 
                    name = '', 
                    created_by = '', 
                    created_after = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    created_before = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    google_place_id = '', 
                    bbox = nauticalstream_workspace.models.b_box.BBox(
                        north_east = nauticalstream_workspace.models.lat_lng.LatLng(
                            latitude = 1.337, 
                            longitude = 1.337, ), 
                        south_west = nauticalstream_workspace.models.lat_lng.LatLng(
                            latitude = 1.337, 
                            longitude = 1.337, ), ), 
                    radius_m = 56, 
                    location = , )
            )
        else:
            return ListWorkspacesRequest(
        )
        """

    def testListWorkspacesRequest(self):
        """Test ListWorkspacesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
