# coding: utf-8

"""
    NauticalStream | workspace-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nauticalstream_workspace.models.list_categories_response import ListCategoriesResponse

class TestListCategoriesResponse(unittest.TestCase):
    """ListCategoriesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListCategoriesResponse:
        """Test ListCategoriesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListCategoriesResponse`
        """
        model = ListCategoriesResponse()
        if include_optional:
            return ListCategoriesResponse(
                items = [
                    nauticalstream_workspace.models.category.Category(
                        id = 56, 
                        status = 'pending', 
                        created_by = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deprecated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deprecated_by = '', 
                        name = '', 
                        key = '', 
                        description = '', 
                        icon = '', )
                    ],
                pagination = nauticalstream_workspace.models.page_response.PageResponse(
                    total = 56, 
                    page = 56, 
                    size = 56, 
                    pages = 56, 
                    has_next_page = True, 
                    has_previous_page = True, )
            )
        else:
            return ListCategoriesResponse(
                items = [
                    nauticalstream_workspace.models.category.Category(
                        id = 56, 
                        status = 'pending', 
                        created_by = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deprecated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deprecated_by = '', 
                        name = '', 
                        key = '', 
                        description = '', 
                        icon = '', )
                    ],
                pagination = nauticalstream_workspace.models.page_response.PageResponse(
                    total = 56, 
                    page = 56, 
                    size = 56, 
                    pages = 56, 
                    has_next_page = True, 
                    has_previous_page = True, ),
        )
        """

    def testListCategoriesResponse(self):
        """Test ListCategoriesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
