# coding: utf-8

"""
    NauticalStream | workspace-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nauticalstream_workspace.models.category_status import CategoryStatus

class TestCategoryStatus(unittest.TestCase):
    """CategoryStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCategoryStatus(self):
        """Test CategoryStatus"""
        # inst = CategoryStatus()

if __name__ == '__main__':
    unittest.main()
