# coding: utf-8

"""
    NauticalStream | workspace-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nauticalstream_workspace.models.page_response import PageResponse

class TestPageResponse(unittest.TestCase):
    """PageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageResponse:
        """Test PageResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageResponse`
        """
        model = PageResponse()
        if include_optional:
            return PageResponse(
                total = 56,
                page = 56,
                size = 56,
                pages = 56,
                has_next_page = True,
                has_previous_page = True
            )
        else:
            return PageResponse(
                total = 56,
                page = 56,
                size = 56,
                pages = 56,
                has_next_page = True,
                has_previous_page = True,
        )
        """

    def testPageResponse(self):
        """Test PageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
