# coding: utf-8

"""
    NauticalStream | workspace-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nauticalstream_workspace.models.amenity_status import AmenityStatus

class TestAmenityStatus(unittest.TestCase):
    """AmenityStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAmenityStatus(self):
        """Test AmenityStatus"""
        # inst = AmenityStatus()

if __name__ == '__main__':
    unittest.main()
