# coding: utf-8

"""
    NauticalStream | workspace-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nauticalstream_workspace.models.amenity_type import AmenityType

class TestAmenityType(unittest.TestCase):
    """AmenityType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAmenityType(self):
        """Test AmenityType"""
        # inst = AmenityType()

if __name__ == '__main__':
    unittest.main()
