# coding: utf-8

"""
    NauticalStream | workspace-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nauticalstream_workspace.models.create_amenity_request import CreateAmenityRequest

class TestCreateAmenityRequest(unittest.TestCase):
    """CreateAmenityRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAmenityRequest:
        """Test CreateAmenityRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAmenityRequest`
        """
        model = CreateAmenityRequest()
        if include_optional:
            return CreateAmenityRequest(
                name = '',
                description = '',
                icon = '',
                type = 'boolean'
            )
        else:
            return CreateAmenityRequest(
                name = '',
        )
        """

    def testCreateAmenityRequest(self):
        """Test CreateAmenityRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
