# coding: utf-8

"""
    NauticalStream | workspace-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nauticalstream_workspace.api.workspaces_api import WorkspacesApi


class TestWorkspacesApi(unittest.TestCase):
    """WorkspacesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkspacesApi()

    def tearDown(self) -> None:
        pass

    def test_activate_amenity(self) -> None:
        """Test case for activate_amenity

        Activate Amenity
        """
        pass

    def test_activate_category(self) -> None:
        """Test case for activate_category

        Activate Category
        """
        pass

    def test_activate_workspace(self) -> None:
        """Test case for activate_workspace

        Activate Workspace
        """
        pass

    def test_activate_workspace_feature(self) -> None:
        """Test case for activate_workspace_feature

        Activate Workspace Feature
        """
        pass

    def test_add_amenity_to_category(self) -> None:
        """Test case for add_amenity_to_category

        Add Amenity To Category
        """
        pass

    def test_are_features_active(self) -> None:
        """Test case for are_features_active

        Are Features Active
        """
        pass

    def test_check_workspace_handle_exists(self) -> None:
        """Test case for check_workspace_handle_exists

        Check Workspace Handle Exists
        """
        pass

    def test_create_amenity(self) -> None:
        """Test case for create_amenity

        Create Amenity
        """
        pass

    def test_create_category(self) -> None:
        """Test case for create_category

        Create Category
        """
        pass

    def test_create_workspace(self) -> None:
        """Test case for create_workspace

        Create Workspace
        """
        pass

    def test_create_workspace_feature(self) -> None:
        """Test case for create_workspace_feature

        Create Workspace Feature
        """
        pass

    def test_deactivate_amenity(self) -> None:
        """Test case for deactivate_amenity

        Deactivate Amenity
        """
        pass

    def test_deactivate_category(self) -> None:
        """Test case for deactivate_category

        Deactivate Category
        """
        pass

    def test_deactivate_workspace(self) -> None:
        """Test case for deactivate_workspace

        Deactivate Workspace
        """
        pass

    def test_deactivate_workspace_feature(self) -> None:
        """Test case for deactivate_workspace_feature

        Deactivate Workspace Feature
        """
        pass

    def test_delete_workspace(self) -> None:
        """Test case for delete_workspace

        Delete Workspace
        """
        pass

    def test_delete_workspace_feature(self) -> None:
        """Test case for delete_workspace_feature

        Delete Workspace Feature
        """
        pass

    def test_deprecate_amenity(self) -> None:
        """Test case for deprecate_amenity

        Deprecate Amenity
        """
        pass

    def test_deprecate_category(self) -> None:
        """Test case for deprecate_category

        Deprecate Category
        """
        pass

    def test_get_amenities_batch(self) -> None:
        """Test case for get_amenities_batch

        Get Amenities Batch
        """
        pass

    def test_get_amenity(self) -> None:
        """Test case for get_amenity

        Get Amenity
        """
        pass

    def test_get_categories_batch(self) -> None:
        """Test case for get_categories_batch

        Get Categories Batch
        """
        pass

    def test_get_category(self) -> None:
        """Test case for get_category

        Get Category
        """
        pass

    def test_get_features_batch(self) -> None:
        """Test case for get_features_batch

        Get Features Batch
        """
        pass

    def test_get_workspace(self) -> None:
        """Test case for get_workspace

        Get Workspace
        """
        pass

    def test_get_workspace_feature(self) -> None:
        """Test case for get_workspace_feature

        Get Workspace Feature
        """
        pass

    def test_get_workspace_features(self) -> None:
        """Test case for get_workspace_features

        Get Workspace Features
        """
        pass

    def test_get_workspaces_batch(self) -> None:
        """Test case for get_workspaces_batch

        Get Workspaces Batch
        """
        pass

    def test_get_workspaces_by_bbox(self) -> None:
        """Test case for get_workspaces_by_bbox

        Get Workspaces By Bbox
        """
        pass

    def test_list_amenities(self) -> None:
        """Test case for list_amenities

        List Amenities
        """
        pass

    def test_list_categories(self) -> None:
        """Test case for list_categories

        List Categories
        """
        pass

    def test_list_workspaces(self) -> None:
        """Test case for list_workspaces

        List Workspaces
        """
        pass

    def test_remove_amenity_from_category(self) -> None:
        """Test case for remove_amenity_from_category

        Remove Amenity From Category
        """
        pass

    def test_update_workspace(self) -> None:
        """Test case for update_workspace

        Update Workspace
        """
        pass

    def test_update_workspace_feature(self) -> None:
        """Test case for update_workspace_feature

        Update Workspace Feature
        """
        pass


if __name__ == '__main__':
    unittest.main()
