# coding: utf-8

"""
    NauticalStream | workspace-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nauticalstream_workspace.api.features_api import FeaturesApi


class TestFeaturesApi(unittest.TestCase):
    """FeaturesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FeaturesApi()

    def tearDown(self) -> None:
        pass

    def test_are_features_active(self) -> None:
        """Test case for are_features_active

        Are Features Active
        """
        pass

    def test_get_features_batch(self) -> None:
        """Test case for get_features_batch

        Get Features Batch
        """
        pass


if __name__ == '__main__':
    unittest.main()
