# coding: utf-8

"""
    NauticalStream | workspace-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nauticalstream_workspace.models.workspace_b_box_query_request import WorkspaceBBoxQueryRequest

class TestWorkspaceBBoxQueryRequest(unittest.TestCase):
    """WorkspaceBBoxQueryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceBBoxQueryRequest:
        """Test WorkspaceBBoxQueryRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceBBoxQueryRequest`
        """
        model = WorkspaceBBoxQueryRequest()
        if include_optional:
            return WorkspaceBBoxQueryRequest(
                bbox = nauticalstream_workspace.models.b_box.BBox(
                    north_east = nauticalstream_workspace.models.lat_lng.LatLng(
                        latitude = 1.337, 
                        longitude = 1.337, ), 
                    south_west = nauticalstream_workspace.models.lat_lng.LatLng(
                        latitude = 1.337, 
                        longitude = 1.337, ), ),
                filters = nauticalstream_workspace.models.workspace_b_box_filters.WorkspaceBBoxFilters(
                    status = 'draft', 
                    category_ids = [
                        56
                        ], )
            )
        else:
            return WorkspaceBBoxQueryRequest(
                bbox = nauticalstream_workspace.models.b_box.BBox(
                    north_east = nauticalstream_workspace.models.lat_lng.LatLng(
                        latitude = 1.337, 
                        longitude = 1.337, ), 
                    south_west = nauticalstream_workspace.models.lat_lng.LatLng(
                        latitude = 1.337, 
                        longitude = 1.337, ), ),
        )
        """

    def testWorkspaceBBoxQueryRequest(self):
        """Test WorkspaceBBoxQueryRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
