# coding: utf-8

"""
    NauticalStream | workspace-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nauticalstream_workspace.models.get_workspaces_batch_request import GetWorkspacesBatchRequest

class TestGetWorkspacesBatchRequest(unittest.TestCase):
    """GetWorkspacesBatchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetWorkspacesBatchRequest:
        """Test GetWorkspacesBatchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetWorkspacesBatchRequest`
        """
        model = GetWorkspacesBatchRequest()
        if include_optional:
            return GetWorkspacesBatchRequest(
                ids = [
                    56
                    ],
                handles = [
                    ''
                    ]
            )
        else:
            return GetWorkspacesBatchRequest(
        )
        """

    def testGetWorkspacesBatchRequest(self):
        """Test GetWorkspacesBatchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
