# coding: utf-8

"""
    NauticalStream | workspace-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nauticalstream_workspace.models.create_feature_request import CreateFeatureRequest

class TestCreateFeatureRequest(unittest.TestCase):
    """CreateFeatureRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateFeatureRequest:
        """Test CreateFeatureRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateFeatureRequest`
        """
        model = CreateFeatureRequest()
        if include_optional:
            return CreateFeatureRequest(
                workspace_id = 56,
                amenity_id = 56
            )
        else:
            return CreateFeatureRequest(
                workspace_id = 56,
                amenity_id = 56,
        )
        """

    def testCreateFeatureRequest(self):
        """Test CreateFeatureRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
