# coding: utf-8

"""
    NauticalStream | workspace-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nauticalstream_workspace.models.list_workspaces_response import ListWorkspacesResponse

class TestListWorkspacesResponse(unittest.TestCase):
    """ListWorkspacesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListWorkspacesResponse:
        """Test ListWorkspacesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListWorkspacesResponse`
        """
        model = ListWorkspacesResponse()
        if include_optional:
            return ListWorkspacesResponse(
                items = [
                    nauticalstream_workspace.models.workspace.Workspace(
                        id = 56, 
                        status = 'draft', 
                        created_by = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deleted_by = '', 
                        type = 'unspecified', 
                        name = '', 
                        handle = '', 
                        description = '', 
                        category_id = 56, 
                        formatted_address = '', 
                        avatar_id = '', 
                        cover_id = '', 
                        location = nauticalstream_workspace.models.point.Point(
                            latitude = 1.337, 
                            longitude = 1.337, ), )
                    ],
                pagination = nauticalstream_workspace.models.page_response.PageResponse(
                    total = 56, 
                    page = 56, 
                    size = 56, 
                    pages = 56, 
                    has_next_page = True, 
                    has_previous_page = True, )
            )
        else:
            return ListWorkspacesResponse(
                items = [
                    nauticalstream_workspace.models.workspace.Workspace(
                        id = 56, 
                        status = 'draft', 
                        created_by = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deleted_by = '', 
                        type = 'unspecified', 
                        name = '', 
                        handle = '', 
                        description = '', 
                        category_id = 56, 
                        formatted_address = '', 
                        avatar_id = '', 
                        cover_id = '', 
                        location = nauticalstream_workspace.models.point.Point(
                            latitude = 1.337, 
                            longitude = 1.337, ), )
                    ],
                pagination = nauticalstream_workspace.models.page_response.PageResponse(
                    total = 56, 
                    page = 56, 
                    size = 56, 
                    pages = 56, 
                    has_next_page = True, 
                    has_previous_page = True, ),
        )
        """

    def testListWorkspacesResponse(self):
        """Test ListWorkspacesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
