# coding: utf-8

"""
    NauticalStream | workspace-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nauticalstream_workspace.models.get_features_batch_response import GetFeaturesBatchResponse

class TestGetFeaturesBatchResponse(unittest.TestCase):
    """GetFeaturesBatchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetFeaturesBatchResponse:
        """Test GetFeaturesBatchResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetFeaturesBatchResponse`
        """
        model = GetFeaturesBatchResponse()
        if include_optional:
            return GetFeaturesBatchResponse(
                ids = {
                    'key' : nauticalstream_workspace.models.feature.Feature(
                        id = '', 
                        status = 'pending', 
                        created_by = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deleted_by = '', 
                        workspace_id = 56, 
                        amenity_id = 56, )
                    },
                workspace_ids = {
                    'key' : [
                        nauticalstream_workspace.models.feature.Feature(
                            id = '', 
                            status = 'pending', 
                            created_by = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deleted_by = '', 
                            workspace_id = 56, 
                            amenity_id = 56, )
                        ]
                    },
                amenity_ids = {
                    'key' : [
                        nauticalstream_workspace.models.feature.Feature(
                            id = '', 
                            status = 'pending', 
                            created_by = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deleted_by = '', 
                            workspace_id = 56, 
                            amenity_id = 56, )
                        ]
                    }
            )
        else:
            return GetFeaturesBatchResponse(
        )
        """

    def testGetFeaturesBatchResponse(self):
        """Test GetFeaturesBatchResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
