# coding: utf-8

"""
    NauticalStream | workspace-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nauticalstream_workspace.api.categories_api import CategoriesApi


class TestCategoriesApi(unittest.TestCase):
    """CategoriesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CategoriesApi()

    def tearDown(self) -> None:
        pass

    def test_activate_category(self) -> None:
        """Test case for activate_category

        Activate Category
        """
        pass

    def test_add_amenity_to_category(self) -> None:
        """Test case for add_amenity_to_category

        Add Amenity To Category
        """
        pass

    def test_create_category(self) -> None:
        """Test case for create_category

        Create Category
        """
        pass

    def test_deactivate_category(self) -> None:
        """Test case for deactivate_category

        Deactivate Category
        """
        pass

    def test_deprecate_category(self) -> None:
        """Test case for deprecate_category

        Deprecate Category
        """
        pass

    def test_get_categories_batch(self) -> None:
        """Test case for get_categories_batch

        Get Categories Batch
        """
        pass

    def test_get_category(self) -> None:
        """Test case for get_category

        Get Category
        """
        pass

    def test_list_categories(self) -> None:
        """Test case for list_categories

        List Categories
        """
        pass

    def test_remove_amenity_from_category(self) -> None:
        """Test case for remove_amenity_from_category

        Remove Amenity From Category
        """
        pass


if __name__ == '__main__':
    unittest.main()
