# coding: utf-8

"""
    NauticalStream | workspace-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nauticalstream_workspace.models.readiness_response import ReadinessResponse

class TestReadinessResponse(unittest.TestCase):
    """ReadinessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReadinessResponse:
        """Test ReadinessResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReadinessResponse`
        """
        model = ReadinessResponse()
        if include_optional:
            return ReadinessResponse(
                status = 'ready',
                database = 'reachable'
            )
        else:
            return ReadinessResponse(
                status = 'ready',
                database = 'reachable',
        )
        """

    def testReadinessResponse(self):
        """Test ReadinessResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
