# coding: utf-8

"""
    NauticalStream | workspace-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nauticalstream_workspace.api.amenities_api import AmenitiesApi


class TestAmenitiesApi(unittest.TestCase):
    """AmenitiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AmenitiesApi()

    def tearDown(self) -> None:
        pass

    def test_activate_amenity(self) -> None:
        """Test case for activate_amenity

        Activate Amenity
        """
        pass

    def test_create_amenity(self) -> None:
        """Test case for create_amenity

        Create Amenity
        """
        pass

    def test_deactivate_amenity(self) -> None:
        """Test case for deactivate_amenity

        Deactivate Amenity
        """
        pass

    def test_deprecate_amenity(self) -> None:
        """Test case for deprecate_amenity

        Deprecate Amenity
        """
        pass

    def test_get_amenities_batch(self) -> None:
        """Test case for get_amenities_batch

        Get Amenities Batch
        """
        pass

    def test_get_amenity(self) -> None:
        """Test case for get_amenity

        Get Amenity
        """
        pass

    def test_list_amenities(self) -> None:
        """Test case for list_amenities

        List Amenities
        """
        pass


if __name__ == '__main__':
    unittest.main()
