# coding: utf-8

"""
    NauticalStream | workspace-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nauticalstream_workspace.models.get_categories_batch_request import GetCategoriesBatchRequest

class TestGetCategoriesBatchRequest(unittest.TestCase):
    """GetCategoriesBatchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCategoriesBatchRequest:
        """Test GetCategoriesBatchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCategoriesBatchRequest`
        """
        model = GetCategoriesBatchRequest()
        if include_optional:
            return GetCategoriesBatchRequest(
                ids = [
                    56
                    ]
            )
        else:
            return GetCategoriesBatchRequest(
        )
        """

    def testGetCategoriesBatchRequest(self):
        """Test GetCategoriesBatchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
