# coding: utf-8

"""
    NauticalStream | workspace-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nauticalstream_workspace.models.list_amenities_request import ListAmenitiesRequest

class TestListAmenitiesRequest(unittest.TestCase):
    """ListAmenitiesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAmenitiesRequest:
        """Test ListAmenitiesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAmenitiesRequest`
        """
        model = ListAmenitiesRequest()
        if include_optional:
            return ListAmenitiesRequest(
                filters = nauticalstream_workspace.models.amenity_filters.AmenityFilters(
                    category_id = 56, 
                    status = 'pending', 
                    name = '', 
                    key = '', ),
                pagination = nauticalstream_workspace.models.page_request.PageRequest(
                    page = 56, 
                    size = 56, )
            )
        else:
            return ListAmenitiesRequest(
        )
        """

    def testListAmenitiesRequest(self):
        """Test ListAmenitiesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
