# coding: utf-8

"""
    NauticalStream | workspace-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CategoryStatus(str, Enum):
    """
    CategoryStatus
    """

    """
    allowed enum values
    """
    PENDING = 'pending'
    ACTIVE = 'active'
    INACTIVE = 'inactive'
    DEPRECATED = 'deprecated'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CategoryStatus from a JSON string"""
        return cls(json.loads(json_str))


