# coding: utf-8

"""
    NauticalStream | workspace-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from nauticalstream_workspace.models.point import Point
from nauticalstream_workspace.models.workspace_status import WorkspaceStatus
from nauticalstream_workspace.models.workspace_type import WorkspaceType
from typing import Optional, Set
from typing_extensions import Self

class UpdateWorkspaceRequest(BaseModel):
    """
    UpdateWorkspaceRequest
    """ # noqa: E501
    status: Optional[WorkspaceStatus] = None
    type: Optional[WorkspaceType] = None
    name: Optional[StrictStr] = None
    handle: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    category_id: Optional[StrictInt] = None
    formatted_address: Optional[StrictStr] = None
    location: Optional[Point] = None
    avatar_id: Optional[UUID] = None
    cover_id: Optional[UUID] = None
    __properties: ClassVar[List[str]] = ["status", "type", "name", "handle", "description", "category_id", "formatted_address", "location", "avatar_id", "cover_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateWorkspaceRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of location
        if self.location:
            _dict['location'] = self.location.to_dict()
        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['type'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if handle (nullable) is None
        # and model_fields_set contains the field
        if self.handle is None and "handle" in self.model_fields_set:
            _dict['handle'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if category_id (nullable) is None
        # and model_fields_set contains the field
        if self.category_id is None and "category_id" in self.model_fields_set:
            _dict['category_id'] = None

        # set to None if formatted_address (nullable) is None
        # and model_fields_set contains the field
        if self.formatted_address is None and "formatted_address" in self.model_fields_set:
            _dict['formatted_address'] = None

        # set to None if location (nullable) is None
        # and model_fields_set contains the field
        if self.location is None and "location" in self.model_fields_set:
            _dict['location'] = None

        # set to None if avatar_id (nullable) is None
        # and model_fields_set contains the field
        if self.avatar_id is None and "avatar_id" in self.model_fields_set:
            _dict['avatar_id'] = None

        # set to None if cover_id (nullable) is None
        # and model_fields_set contains the field
        if self.cover_id is None and "cover_id" in self.model_fields_set:
            _dict['cover_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateWorkspaceRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "type": obj.get("type"),
            "name": obj.get("name"),
            "handle": obj.get("handle"),
            "description": obj.get("description"),
            "category_id": obj.get("category_id"),
            "formatted_address": obj.get("formatted_address"),
            "location": Point.from_dict(obj["location"]) if obj.get("location") is not None else None,
            "avatar_id": obj.get("avatar_id"),
            "cover_id": obj.get("cover_id")
        })
        return _obj


